
DROP TABLE RESERVATION;
DROP TABLE RESERVATION_HISTORY;

DROP TABLE CAMPAIGN_DETAILS;
DROP TABLE CAMPAIGN;
DROP TABLE PARKING;



DROP TABLE TARRIFF;
DROP TABLE PRICE_BAND;
DROP TABLE MEASURE_UNIT;
DROP TABLE DISCOUNT;

quit;