CREATE TABLE CHARGES
(
  CHARGE_ID NUMBER PRIMARY KEY,
  CHARGE_DATE DATE NOT NULL,
  RESERVATION_ID NUMBER NOT NULL ,
  PRICE NUMBER(10,2) NOT NULL
);

alter table charges add (canceled CHAR(1) DEFAULT 'N');