CREATE TABLE 
    "PARKING" (
        "ADDRESS" VARCHAR2(1000) NOT NULL, CONSTRAINT "SYS_C004025" CHECK ("ADDRESS" IS NOT NULL) , 
        "CITY" VARCHAR2(200) NOT NULL, CONSTRAINT "SYS_C004026" CHECK ("CITY" IS  NOT NULL) , 
        "COUNTRY" VARCHAR2(200) NOT NULL, CONSTRAINT "SYS_C004028" CHECK ("COUNTRY" IS   NOT NULL) , 
        "NAME" VARCHAR2(200) NOT NULL, CONSTRAINT "SYS_C004024" CHECK ("NAME" IS  NOT NULL) , 
        "PARKING_ID" NUMBER NOT NULL, CONSTRAINT "SYS_C004023" CHECK ("PARKING_ID" IS  NOT NULL) , 
        "REGION" VARCHAR2(200) NOT NULL, CONSTRAINT "SYS_C004027" CHECK ("REGION" IS   NOT NULL) , 
        CONSTRAINT "PK_PARKING_ID" PRIMARY KEY ("PARKING_ID") ) ;
        
quit;        