CREATE TABLE 
    "RESERVATION_HISTORY" (
        "PARKING" NUMBER  NOT NULL, CONSTRAINT "SYS_C004034_hist" CHECK ("PARKING" IS  NOT NULL)  , 
        "RESERVATION_DATE" TIMESTAMP NOT NULL, CONSTRAINT "SYS_C004030_hist" CHECK ("RESERVATION_DATE" IS  NOT NULL) ,
        "RESERVATION_FROM" TIMESTAMP NOT NULL, CONSTRAINT "SYS_C004031_hist" CHECK ("RESERVATION_FROM" IS  NOT NULL) , 
        "RESERVATION_ID" NUMBER (38, 0) NOT NULL, CONSTRAINT "SYS_C004029_hist" CHECK ("RESERVATION_ID" IS   NOT NULL) ,
        "RESERVATION_TO" TIMESTAMP NOT NULL, CONSTRAINT "SYS_C004032_hist" CHECK ("RESERVATION_TO" IS  NOT NULL) , 
        "VEHICLE_NUMBER" VARCHAR2 (4000) NOT NULL, CONSTRAINT "SYS_C004033_hist" CHECK ("VEHICLE_NUMBER"  IS  NOT NULL) ,
         CONSTRAINT "FK_parking_HIST" FOREIGN KEY ("PARKING") REFERENCES "PARKING" ("PARKING_ID") ) ;

alter table reservation_history add (canceled char(1) default 'N');

quit;         